# docker/Dockerfile.consumer

FROM python:3.10-slim

WORKDIR /app

COPY src/consumer/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/consumer/ .

# expose the port the app runs on for flask
EXPOSE 8000

CMD ["python", "app.py"]
